Всем привет!

Это ваше первое домашнее задание))

Списывать нельзя, гуглить можно)

Что надо помнить: пишите код красиво, контролируйте код-стайл, нормальную структуру, импорты и все, что мы говорили на занятиях.

Дедлайн: пятница 17 ноября в 23:59

Решения на почту - skvortsovg@yandex.ru

Пожалуйста, напишите в теме письма так: **ФТиАД23: python_дз1 Фамилия Имя**

### Задача 1 (расстояние между точками на земле)

Напишите программу, в которой пользователь будет вводить координаты двух точек на Земле (широту и долготу) в градусах. На выходе должно получиться расстояние между этими точками при следовании по кратчайшему пути по поверхности планеты.



In [ ]:
from math import sin, cos, sqrt, atan2, radians

R = 6373.0

lat1, lon1 = radians(float(input())), radians(float(input()))
lat2, lon2 = radians(float(input())), radians(float(input()))

a = sin((lat2 - lat1) / 2)**2 + cos(lat1) * cos(lat2) * sin((lon2 - lon1) / 2)**2
c = 2 * atan2(sqrt(a), sqrt(1 - a))

print("Result distance: ", R * c)

52.2296756
21.0122287
52.406374
16.9251681
Result distance:  278.54558935106695


### Задача 2 (максимальная сумма)

Ввести в столбик последовательность целых (положительных и отрицательных) чисел, не равных нулю; в конце этой последовательности стоит 0. Вывести наибольшую сумму последовательно идущих элементов этой последовательности (не менее одного).



In [ ]:
lst = []
while (a := int(input())):
  if a == 0 : break
  lst.append(a)
print(lst, len(lst))

max_sum, prev_sum, glob_max_sum = 0, 0, 0

for i in range(0, len(lst)):
  if i == 0:
    max_sum = sum(lst)
    glob_max_sum = max_sum
  else:
    max_sum = sum(lst[:i])
    prev_sum = max_sum
    for j in range(0, len(lst) - i):
      max_sum = max_sum - lst[j] + lst[i+j]
      if (prev_sum < max_sum):
        prev_sum = max_sum
    if prev_sum > glob_max_sum:
      glob_max_sum = prev_sum
print(glob_max_sum)


-5
-1
-3
0
[-5, -1, -3] 3
-1


### Задача 3 (сумма кубов)

Ввести натуральное число N и вывести, сколько существует различных пар натуральных чисел A и B: A³+B³=N (с точностью до перестановки).  Вещественные операции (например, кубический корень) рекомендуется использовать как можно реже.

In [ ]:
!pip install gmpy2


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 15.4 MB/s eta 0:00:00


In [ ]:
import gmpy2

N = int(input())
pairs_count = 0
for  i in range(int(N ** (1/3))):
  #print(i, gmpy2.root((N - i**3), 3))
  if gmpy2.root((N - i**3), 3) % 1 == 0:
    pairs_count += 1
print(pairs_count)

128
1


### Задача 4 (Разложение на множители)
Ввести произвольное натуральное число, не превосходящее 1000000000

Вывести (через «*») все его разложения на натуральные сомножители, превосходящие 1, без учёта перестановок. Сомножители в каждом разложении и сами разложения (как последовательности) при выводе должны быть упорядочены по возрастанию. Само число также считается разложением.

In [ ]:
def multipliers(N, prev_st=''):
  lst = []
  for i in range(2, int(N ** 0.5)+1):
    if N % i == 0:
      if prev_st == '':
        multipliers(int(N // i), str(i))
        print(str(i) + '*' + str(int(N // i)))
      else:
        multipliers(int(N // i), prev_st +'*' + str(i))
        num_str = prev_st + '*' + str(i) + '*' + str(int(N // i))

        if sorted(num_str.split('*')) == num_str.split('*'):
          print( prev_st + '*' + str(i) + '*' + str(int(N // i)))
      lst.append(int(N // i))
  if prev_st == '':
    print(str(N))

N = int(input())
multipliers(N)


12
2*2*3
2*6
3*4
12


### Задача 5 (Переворот числа)
Пусть на вход дается челое 32-х битное число (может быть и отрицательное)

Необходимо вернуть его перевернутую версию, например, для числа -123 ответом будет -321, а для числа -1 будет 1, а для 10101010 - 101010

Пользоваться строковыми методами *нельзя*

In [15]:
n = [*input()]

for i in range(len(n) // 2 ):
  n[i], n[len(n) - i - 1] = n[len(n) - i - 1], n[i]

if n[-1] == '-':
  n[-1] = ''
  print('-' +''.join(n))
else:
  print(''.join(n))


-1
-1


### Задача 6 (Перевод числа в римской записи а арабскую):

На вход подается строка, представляющая натуральное число в римской записи (из символов I, V, X, C, L, M). Требуется представить его в арабской записи. Подробнее про арабские числа можно почитать на [википедии](https://ru.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BC%D1%81%D0%BA%D0%B8%D0%B5_%D1%86%D0%B8%D1%84%D1%80%D1%8B)

In [59]:
dct = {"I" : 1,  "V": 5,  "X": 10,  "L": 50,
      "C": 100,  "D": 500, "M": 1000
    };

def get_arab_num(roman_num):
  arab_num = dct[roman_num[0]]
  for i in range(1, len(roman_num)):
    arab_num += dct[roman_num[i]]
    if dct[roman_num[i - 1]] < dct[roman_num[i]]:
        arab_num -=  2 * dct[roman_num[i - 1]]
  return arab_num


print(get_arab_num(input()))

MCMLI
1951


### Задача 7 (Группировка итератора)

Напишите итератор (вспомните про **yield**), которая возвращает строку длины N

Напишите вспомогательную функцию, которая будет принимать результат итератора и комбинировать его в чанки заданной длины


In [ ]:
def my_string_generator(N):
  #yield 'a' * N
  gen_str = 'a'
  for i in range(N):
    yield gen_str
    gen_str += 'a'

def chanker(iterable, chunk_size=2) -> tuple:
  for st in iterable:
    res = []
    for i in range(0, len(st), chunk_size):
      res.append(st[i:i + chunk_size])
    yield res


N = 10
chank_size=3

for chank in chanker(my_string_generator(N), 3):
    print(chank)


['a']
['aa']
['aaa']
['aaa', 'a']
['aaa', 'aa']
['aaa', 'aaa']
['aaa', 'aaa', 'a']
['aaa', 'aaa', 'aa']
['aaa', 'aaa', 'aaa']
['aaa', 'aaa', 'aaa', 'a']


### Задача 8 (Декоратор-ретрай)

Напишите функцию, которая принимает число N и с вероятностью 1/N возвращает строку, а в остальных случаях порождает исключение.

Напишите декоратор, который пытается выполнить функцию заданное кол-во раз и задекорируйте ее.


In [ ]:
import random

def dec_retry(func):
  def wrapper(N):
    try:
      for i in range(N):
        func(N)
    except NameError:
      print('exception')
  return wrapper

@dec_retry
def retry(N):
  r = random.uniform(0, 1)
  if r < 1/N:
    print(r)
    return 'DecoratorRetryError'
  raise NameError('DecoratorRetryError')

retry(2)

0.3028045309094757
exception


### Задание 9 (Использование паттера Singleton)

Найдите на github примеры кода (5 штук), где применяется паттерн singleton. У репозитория, в которым вы ищите, должно быть более 10 звездочек.

Ниже вставьте примеры такого кода (5 штук) и напишите где именно используется паттерн и зачем

In [ ]:
https://github.com/reyoung/singleton
https://github.com/lazybird/django-solo
https://github.com/boberle/cofr
https://github.com/ets-labs/python-dependency-injector
https://github.com/stoic1979/PyLogger

### Задача 10 (Решатель судоку)

Напишите программу, которая принимает матричку 9*9 (список списков), которая представляет собой кроссворд-судоку.
В местах, куда надо вставить значения - -**1**

И напишите функцию (функции), которые решают судоку и выводят результат

In [9]:
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def possible(row, column, number):
    global grid
    for i in range(0,9):
        if grid[row][i] == number:
            return False
    for i in range(0,9):
        if grid[i][column] == number:
            return False
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False
    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0
                return
    print(np.matrix(grid))

solve()



[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


### Задача 11 (сколько гостей было в отеле одномоментно)
Представьте, что вы - менеджер отеля и хотите знать, сколько гостей было в отеле максимально за весь период.

Каждый гость характеризуется тюплом (day_start, day_end), который показывает, когда гость заселился и выселился из отеля. Имейте в виду, что время заселения всегда больше, чем время выселения, то есть гости (1, 6) и (6, 8) не пересекались друг с другом.

Напишите функцию, которая позволяет определить, сколько гостей в отеле было максимально. Входные данные вышей функции - список из тюплов.

Примеры:

    1. [(0, 1), (1, 2), (0, 3)] -> 2
    2. [(10, 20), (5, 7), (5, 20), (20, 21)] -> 3

In [90]:
hotel = {}

guests = [(10, 20), (5, 7), (5, 20), (20, 21)]
min_day = min(guests, key = lambda item: item[0])[0]
max_day = max(guests, key = lambda item: item[1])[1]
for i in range(min_day, max_day):
  hotel[i] = 0
for g in guests:
  for i in range(g[0], g[1]):
    hotel[i] += 1

#print(hotel)
print(max(hotel.values()))

2


In [91]:
guests = [(10, 20), (5, 7), (5, 20), (20, 21)]
min_day = min(guests, key = lambda item: item[0])[0]
max_day = max(guests, key = lambda item: item[1])[1]

for g in guests:
  for i in range(min_day, g[0]):
    print('o', end='')
  for i in range(g[0], g[1]):
    print('-', end='') #присутствие гостя в отеле
  for i in range(g[1], max_day):
    print('o', end='')
  print()

ooooo----------o
--oooooooooooooo
---------------o
ooooooooooooooo-


На рисунке выше максимальное число пересечений отрезков одновременно - 2, день выезда гостя - o, т. е. считаем, что он отсутствовал (исходя из условия). Тогда правильный ответ в примере 2 - 2


### Задача 12 (проверка на центр отрезка)

Пусть у вас есть 3 числа - первые два задают начало и конец отрезка, а третье - предполагаемую середину. Все вводные значения - float

Необходимо написать функцию, которая проверяет, является ли третье число серединой отрезка.


In [67]:
x1, y1 = [int(x) for x in input().split()]
x2, y2 = [int(x) for x in input().split()]
x3, y3 = [int(x) for x in input().split()]

def middle(a, b):
  if a*b > 0:
    return (a + b) / 2
  return (abs(a) + abs(b)) / 2 + min(a, b)

def check_middle(x1, y1, x2, y2, x3, y3):
  #print(x1, x2, middle(x1, x2))
  #print(y1, y2, middle(y1, y2))
  if x3 == middle(x1, x2) and  y3 == middle(y1, y2):
    return True
  return False

print(check_middle(x1, y1, x2, y2, x3, y3))


-1 10
5 -2
2 4
True


### Задача 13 (классы)

Это задача дает большой простор для креатива. Вам надо написать класс (или классы), где вы продемонстрируйте владение такими штуками, как проперти, классметод, статикметод, магические методы (достаточно показать владение несколькими из них).

In [18]:
class ClassDescriptor(object):

    def __init__(self, fget, fset=None):
        self.fget = fget
        self.fset = fset

    def __get__(self, obj, klass=None):
        if klass is None:
            klass = type(obj)
        return self.fget.__get__(obj, klass)()

    def __set__(self, obj, value):
        type_ = type(obj)
        return self.fset.__get__(obj, type_)(value)

    def setter(self, func):
        if not isinstance(func, (classmethod, staticmethod)):
            func = classmethod(func)
        self.fset = func
        return self

def classdesc(func):
    if not isinstance(func, (classmethod, staticmethod)):
        func = classmethod(func)

    return ClassDescriptor(func)


class Bar(object):

    _bar = 1

    @classdesc
    def bar(cls):
        return cls._bar

    @bar.setter
    def bar(cls, value):
        cls._bar = value


# test instance instantiation
foo = Bar()
assert foo.bar == 1

baz = Bar()
assert baz.bar == 1

# test static variable
baz.bar = 5
assert foo.bar == 5

# test setting variable on the class
Bar.bar = 50
assert baz.bar == 50
assert foo.bar == 50